const PDFDocument = require('pdfkit');
const fs = require('fs');
const { generateOutputPath } = require('../utils/fileUtils');

async function htmlToPdf(url) {
  // Fetch the HTML content
  const response = await fetch(url, {
    headers: { 'User-Agent': 'Mozilla/5.0 (compatible; PDFSpark/1.0)' },
    signal: AbortSignal.timeout(15000),
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch URL: ${response.status} ${response.statusText}`);
  }

  const html = await response.text();

  // Extract text content from HTML
  const textContent = extractText(html);
  const pageTitle = extractTitle(html);

  // Create PDF with pdfkit
  const outputPath = generateOutputPath('pdf');
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const stream = fs.createWriteStream(outputPath);

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(outputPath));
    stream.on('error', reject);
    doc.pipe(stream);

    // Title
    if (pageTitle) {
      doc.fontSize(20).font('Helvetica-Bold').text(pageTitle, { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(8).fillColor('#888').text(`Source: ${url}`, { align: 'center' });
      doc.moveDown(1);
      doc.fillColor('#000');
    }

    // Horizontal line
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
    doc.moveDown(1);

    // Body content
    const lines = textContent.split('\n');
    doc.fontSize(11).font('Helvetica');

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) {
        doc.moveDown(0.5);
        continue;
      }
      // Detect heading-like lines (short, no period at end)
      if (trimmed.length < 80 && !trimmed.endsWith('.') && !trimmed.endsWith(',')) {
        doc.font('Helvetica-Bold').fontSize(13).text(trimmed);
        doc.font('Helvetica').fontSize(11);
        doc.moveDown(0.3);
      } else {
        doc.text(trimmed, { lineGap: 2 });
      }
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#888')
      .text(`Generated by PDFSpark from ${url}`, 50, doc.page.height - 50, { align: 'center' });

    doc.end();
  });
}

function extractTitle(html) {
  const match = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  return match ? match[1].trim().replace(/&[^;]+;/g, ' ') : '';
}

function extractText(html) {
  let text = html;
  // Remove script/style tags and their content
  text = text.replace(/<script[\s\S]*?<\/script>/gi, '');
  text = text.replace(/<style[\s\S]*?<\/style>/gi, '');
  text = text.replace(/<noscript[\s\S]*?<\/noscript>/gi, '');
  // Convert block elements to newlines
  text = text.replace(/<\/?(div|p|br|h[1-6]|li|tr|blockquote|section|article|header|footer|nav|main)[^>]*>/gi, '\n');
  // Remove remaining HTML tags
  text = text.replace(/<[^>]+>/g, '');
  // Decode common HTML entities
  text = text.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>');
  text = text.replace(/&nbsp;/g, ' ').replace(/&quot;/g, '"').replace(/&#39;/g, "'");
  text = text.replace(/&[a-z]+;/gi, ' ');
  // Clean up whitespace
  text = text.replace(/[ \t]+/g, ' ');
  text = text.replace(/\n\s*\n/g, '\n\n');
  return text.trim();
}

module.exports = { htmlToPdf };
